import {state} from './model.js';
const NS='http://www.w3.org/2000/svg';
export function pacemakerPoint(u){
  if(u<.6)return {mv:-60+20*(u/.6)**1.3,phase:'4',title:'Slow diastolic depolarization',ions:'Net inward funny current (Iƒ), calcium entry and declining outward potassium current bring the cell toward threshold.'};
  if(u<.68)return {mv:-40+50*Math.sin((u-.6)/.08*Math.PI/2),phase:'0',title:'Depolarization · calcium enters',ions:'L-type Ca²⁺ channels open. Inward calcium current produces the nodal upstroke.'};
  return {mv:10-70*(1-Math.cos((u-.68)/.32*Math.PI))/2,phase:'3',title:'Repolarization · potassium leaves',ions:'Ca²⁺ current declines and outward K⁺ current makes the membrane negative again, returning toward its maximum diastolic potential.'};
}
export function createAnatomyHover(){
 const tip=document.createElement('aside');tip.id='anatomy-tooltip';tip.className='anatomy-tooltip';tip.setAttribute('role','tooltip');tip.hidden=true;document.body.append(tip);
 let active=null,cycle=0,last=performance.now(),suppressed=false;
 function hide(){if(active)active.removeAttribute('aria-describedby');active=null;tip.hidden=true;}
 function position(){if(!active)return;const r=active.getBoundingClientRect(),w=Math.min(370,innerWidth-24);tip.style.width=w+'px';let left=r.right+18;if(left+w>innerWidth-12)left=r.left-w-18;left=Math.max(12,Math.min(left,innerWidth-w-12));tip.style.left=left+'px';tip.style.top=Math.max(12,Math.min(r.top-20,innerHeight-tip.offsetHeight-12))+'px';}
 function show(target,name,node){if(suppressed)return;hide();active=target;target.setAttribute('aria-describedby',tip.id);cycle=0;last=performance.now();tip.dataset.node=node||'';tip.replaceChildren();const title=document.createElement('strong');title.textContent=name;tip.append(title);const close=document.createElement('button');close.className='anatomy-dismiss';close.textContent='Close';close.setAttribute('aria-label','Close anatomy detail');close.onclick=hide;tip.append(close);
 if(node){const content=document.createElement('div');content.innerHTML=`<p class="cell-caption">Nodal cell action potential · schematic</p><svg class="cell-chart" viewBox="0 0 340 190" role="img" aria-label="Membrane voltage in millivolts versus one illustrative nodal cycle, showing phases 4, 0 and 3"><path d="M42 16V155H323" fill="none" stroke="#7e98a5"/><g fill="#bcd0da" font-size="12"><text x="5" y="20">mV</text><text x="9" y="45">+10</text><text x="9" y="112">−40</text><text x="9" y="146">−60</text><text x="62" y="178">4 · drift</text><text x="204" y="178">0</text><text x="270" y="178">3</text></g><path d="M42 115H323" stroke="#8ca1b0" stroke-dasharray="4 5"/><text x="47" y="102" fill="#9db5bf" font-size="11">Threshold ≈ −40 mV</text><path id="cell-curve" fill="none" stroke="#70e5cf" stroke-width="3"/><line id="cell-cursor" y1="25" y2="153" stroke="#ffe363" stroke-dasharray="3 4"/><circle id="cell-point" r="5" fill="#ffe363"/></svg><div class="cell-stage"></div><p class="cell-ions"></p><p class="cell-note">${node==='av'?'The AV node is normally driven by incoming atrial impulses; this illustrates its slow-response cell physiology.':'The SA node normally initiates the sinus beat.'} This illustrative cycle is not time-aligned to the ECG. Returning near −60 mV helps activate Iƒ; hyperpolarization is not a separate numbered phase. Values vary between cells.</p>`;tip.append(content);let d='';for(let i=0;i<=200;i++){const u=i/200,v=pacemakerPoint(u).mv;d+=(i?'L':'M')+(42+u*280)+','+(145-(v+60)*1.5);}tip.querySelector('#cell-curve').setAttribute('d',d);}
 tip.hidden=false;update(performance.now());position();
 }
 function bind(target,name,node){target.setAttribute('tabindex','0');target.setAttribute('aria-label',name);target.classList.add('anatomy-target');target.addEventListener('pointerenter',e=>{if(e.pointerType==='touch')return;suppressed=false;show(target,name,node);});target.addEventListener('pointerleave',e=>{if(e.pointerType!=='touch')hide();});target.addEventListener('click',e=>{if(!matchMedia('(hover: none)').matches)return;e.stopPropagation();suppressed=false;show(target,name,node);});target.addEventListener('focus',()=>{suppressed=false;show(target,name,node);});target.addEventListener('blur',hide);}
 function update(now){const dt=Math.min((now-last)/1000,.1);last=now;if(tip.hidden||!tip.dataset.node)return;if(state.playing)cycle=(cycle+dt*state.speed/.8)%1;const p=pacemakerPoint(cycle),x=42+cycle*280,y=145-(p.mv+60)*1.5;tip.querySelector('#cell-point').setAttribute('cx',x);tip.querySelector('#cell-point').setAttribute('cy',y);tip.querySelector('#cell-cursor').setAttribute('x1',x);tip.querySelector('#cell-cursor').setAttribute('x2',x);tip.querySelector('.cell-stage').textContent=`Phase ${p.phase} · ${p.title} · ${Math.round(p.mv)} mV`;tip.querySelector('.cell-ions').textContent=p.ions;}
 document.addEventListener('pointerdown',e=>{if(active&&!active.contains(e.target)&&!tip.contains(e.target))hide();});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){suppressed=true;hide();}});window.addEventListener('scroll',hide,true);window.addEventListener('resize',hide);
 function attach(svg,anatomy,routes,points,view){hide();const names=view==='frontal'?['Right atrium','Left atrium','Right ventricle','Left ventricle']:['Right ventricle','Left ventricle'];anatomy.querySelectorAll('.right-cavity,.left-cavity').forEach((path,i)=>bind(path,names[i]));bind(anatomy.querySelector('.wall'),'Myocardium · heart muscle');const valves=anatomy.querySelector('.valve');if(valves)bind(valves,'Atrioventricular valves');
 const group=document.createElementNS(NS,'g');group.setAttribute('class','anatomy-hit-regions');svg.append(group);
 for(const {edge,base}of routes){let name=edge.id.startsWith('his')?'Bundle of His':edge.id==='septal'?'Interventricular septal myocardium':edge.kind==='atrial'?'Atrial myocardium · conduction toward AV node':edge.kind==='tissue'?'Ventricular myocardium':edge.kind==='purkinje'?'Purkinje fibers':edge.side<0?'Right bundle branch':'Left bundle branch';const hit=document.createElementNS(NS,'path');hit.setAttribute('d',base.getAttribute('d'));hit.setAttribute('class','anatomy-hit-path');group.append(hit);bind(hit,name);}
 for(const [key,name]of [['sa','Sinoatrial (SA) node'],['av','Atrioventricular (AV) node']]){const hit=document.createElementNS(NS,'circle');hit.setAttribute('cx',points[key][0]);hit.setAttribute('cy',points[key][1]);hit.setAttribute('r','18');hit.setAttribute('class','anatomy-hit-node');hit.dataset.anatomy=key;group.append(hit);bind(hit,name,key);}
 }
 return {attach,update};
}
