import {appearance,initSettings} from './settings.js';
import {patterns,leads,state,configure,voltage,phase,beats} from './model.js';
import {initHeart} from './heart.js';
import {initInspector,signalColor} from './inspector.js';
const $=id=>document.getElementById(id);let heart;
$('rhythm').innerHTML=Object.entries(patterns).map(([k,p])=>`<option value="${k}">${p.name}</option>`).join('');
const mini=leads.map((l,i)=>{const btn=document.createElement('button');btn.className='lead-button';btn.setAttribute('aria-label',`Select lead ${l.name}, ${l.region}`);btn.innerHTML=`<span>${l.name}</span><canvas aria-hidden="true"></canvas>`;btn.onclick=()=>selectLead(i);$('leads').append(btn);return {btn,canvas:btn.querySelector('canvas')};});
function selectLead(i){state.lead=i;const l=leads[i];$('selectedLead').textContent='Lead '+l.name;$('territory').textContent=l.region;$('leadName').textContent=l.name+' · '+l.region+' view';$('leadDescription').textContent=l.desc;$('leadPlane').textContent=l.angle!==undefined?'FRONTAL PLANE · '+(l.angle>0?'+':'')+l.angle+'°':'HORIZONTAL PLANE · CHEST ELECTRODE';mini.forEach((x,n)=>{x.btn.classList.toggle('active',n===i);x.btn.setAttribute('aria-pressed',n===i);});dirty=true;}
function playLabel(){$('play').textContent=state.playing?'Ⅱ Pause':'▶ Play';$('live').textContent=state.playing?'● LIVE':'Ⅱ PAUSED';}
let dirty=true,stripCache=[],miniCache=[];
function setPattern(key){configure(key);$('rhythm').value=key;const p=patterns[key];$('rate').innerHTML=(p.rate===null?'—':(key==='af'?'~':'')+p.rate)+' <small>bpm</small>';$('pr').innerHTML=(p.pr===null?'—':Math.round(p.pr*1000))+' <small>ms</small>';$('qrs').innerHTML=(p.qrs===null?'—':key==='pvc'?'90 / 170':Math.round(p.qrs*1000))+' <small>ms</small>';$('patternTitle').textContent=p.title;$('patternText').textContent=p.text;dirty=true;}
$('rhythm').onchange=e=>setPattern(e.target.value);$('play').onclick=()=>{state.playing=!state.playing;playLabel();};$('speed').onchange=e=>state.speed=+e.target.value;$('reset').onclick=()=>{state.time=0;};$('time').oninput=e=>{state.time=+e.target.value;state.playing=false;playLabel();};$('guideBtn').onclick=()=>{$('guide').open=true;$('guide').scrollIntoView({behavior:'smooth'});};
try{heart=initHeart($('scene'),selectLead);}catch(e){$('scene').textContent='The cross-section could not load. Please refresh.';console.error(e);}
const inspector=initInspector(t=>{state.time=Math.max(0,Math.min(6,t));state.playing=false;playLabel();});

$('strip').style.cursor='crosshair';$('strip').onclick=e=>{const r=$('strip').getBoundingClientRect();state.time=Math.max(0,Math.min(6,(e.clientX-r.left-28)/(r.width-38)*6));state.playing=false;playLabel();};
$('showLeads').onchange=e=>heart?.setLeads(e.target.checked);$('showLabels').onchange=e=>heart?.setLabels(e.target.checked);for(const id of ['front','side'])$(id).onclick=()=>heart?.view(id);
document.querySelectorAll('[data-route-step]').forEach(button=>button.onclick=()=>{const b=beats.find(b=>b.q>.4&&!b.pvc);if(!b)return;const pr=patterns[state.key].pr||.16;const offsets={sa:-pr+.012,av:-.050,his:-.018,bundle:.010,muscle:.057};state.time=b.q+offsets[button.dataset.routeStep];state.playing=false;playLabel();});
const phases=[['P','P wave'],['PR','PR'],['QRS','QRS'],['ST','ST'],['T','T wave']];phases.forEach(([id,name])=>{const b=document.createElement('button');b.textContent=name;b.dataset.phase=id;b.onclick=()=>{if(['af','flutter','vf','vt'].includes(state.key)&&['P','PR'].includes(id))return;let beat=beats.find(x=>x.q>.4&&!x.pvc)||beats[0];if(!beat)return;const p=patterns[state.key],rec=['tachy','flutter','vt'].includes(state.key)?.12:.2;state.time=Math.max(0,Math.min(6,beat.q+({P:-(p.pr||.16)+.045,PR:-.025,QRS:beat.d*.45,ST:beat.d+.015,T:beat.d+rec}[id])));state.playing=false;playLabel();};$('phaseButtons').append(b);});
function canvasSize(canvas){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);if(canvas.width!==Math.round(r.width*d)||canvas.height!==Math.round(r.height*d)){canvas.width=Math.round(r.width*d);canvas.height=Math.round(r.height*d);dirty=true;}return{w:r.width,h:r.height,d};}
function base(canvas,idx,small=false){const {w,h,d}=canvasSize(canvas),ctx=canvas.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const duration=6,pad=small?6:28,usable=w-pad-10,pxsec=usable/duration,pxmv=pxsec*.4*appearance.gain,baseline=small?h*.65:h*.63;
if(!small){for(let x=pad;x<w;x+=pxsec*.04){let n=Math.round((x-pad)/(pxsec*.04));ctx.strokeStyle=n%5===0?'#274139':'#152d2c';ctx.lineWidth=.5;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=baseline% (pxmv*.1);y<h;y+=pxmv*.1){ctx.strokeStyle=Math.round((y-baseline)/(pxmv*.1))%5===0?'#274139':'#152d2c';ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.fillStyle='#758c8c';ctx.font='9px monospace';ctx.fillText('mV',4,12);ctx.fillText('1',7,baseline-pxmv+3);ctx.fillText('0',7,baseline+3);for(let s=0;s<=6;s++)ctx.fillText(s+'s',pad+s*pxsec-5,h-5);}
let previous=null;for(let x=0;x<=usable;x+=.25){let t=x/usable*duration;let y=baseline-voltage(t,idx)*(small?17*appearance.gain:pxmv);if(previous){ctx.beginPath();ctx.moveTo(pad+previous.x,previous.y);ctx.lineTo(pad+x,y);ctx.strokeStyle=signalColor(t);ctx.globalAlpha=small&&idx!==state.lead?.78:1;ctx.lineWidth=small?Math.max(1,appearance.width*.6):appearance.width;ctx.lineCap='round';ctx.stroke();}previous={x,y};}ctx.globalAlpha=1;return {image:ctx.getImageData(0,0,canvas.width,canvas.height),w,h,d,pad,usable,duration,baseline,pxmv,ctx};}
function cursor(cache,canvas,small=false){const{ctx,d,pad,usable,duration,h}=cache;ctx.putImageData(cache.image,0,0);ctx.setTransform(d,0,0,d,0,0);if(state.time>duration)return;const x=pad+state.time/duration*usable;ctx.strokeStyle=small?'#ffe49a8c':'#ffe49a';ctx.lineWidth=1;ctx.setLineDash(small?[]:[3,3]);ctx.beginPath();ctx.moveTo(x,small?19:0);ctx.lineTo(x,h-(small?0:15));ctx.stroke();ctx.setLineDash([]);if(!small){const y=cache.baseline-voltage(state.time,state.lead)*cache.pxmv;ctx.fillStyle=signalColor(state.time);ctx.shadowColor=signalColor(state.time);ctx.shadowBlur=10;ctx.beginPath();ctx.arc(x,y,5,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}}
let last=performance.now(),lastText=0;function frame(now){const delta=Math.min((now-last)/1000,.08);last=now;if(state.playing){state.time+=delta*state.speed;if(state.time>6)state.time=0;}if(dirty){stripCache=base($('strip'),state.lead);miniCache=mini.map((x,i)=>base(x.canvas,i,true));dirty=false;}cursor(stripCache,$('strip'));mini.forEach((x,i)=>cursor(miniCache[i],x.canvas,true));heart?.render(state.time);inspector.render(state.time);if(now-lastText>60){const p=phase(state.time);document.querySelectorAll('[data-route-step]').forEach(b=>b.disabled=['af','flutter','vt','vf'].includes(state.key));$('phaseIcon').textContent=p.id;$('phaseIcon').style.color=signalColor(state.time);$('phaseIcon').style.borderColor=signalColor(state.time);$('phaseIcon').style.background=p.id==='T'?'#342142':'#3c3725';$('phaseTitle').textContent=p.title;$('phaseText').textContent=p.text;$('time').value=state.time;$('timeText').textContent=state.time.toFixed(2)+' s';const v=voltage(state.time,state.lead);$('voltage').innerHTML=(v>=0?'+':'')+v.toFixed(2)+' <small>mV</small>';$('polarity').textContent=Math.abs(v)<.03?'Near the baseline':v>0?'Positive lead projection':'Negative lead projection';document.querySelectorAll('[data-phase]').forEach(b=>{b.classList.toggle('active',b.dataset.phase===p.id);b.disabled=(state.key==='vf')||(['af','flutter','vt'].includes(state.key)&&['P','PR'].includes(b.dataset.phase));});lastText=now;}requestAnimationFrame(frame);}new ResizeObserver(()=>dirty=true).observe($('strip'));initSettings(()=>dirty=true);selectLead(1);setPattern('sinus');playLabel();requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_ecg_lab',title:'Configure ECG lab',description:'Select a rhythm and ECG lead; optionally pause at a specific simulation time.',inputSchema:{type:'object',properties:{rhythm:{type:'string',enum:Object.keys(patterns)},lead:{type:'string',enum:leads.map(l=>l.name)},time:{type:'number',minimum:0,maximum:6}},required:['rhythm','lead'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||!patterns[input.rhythm]||!leads.some(l=>l.name===input.lead)||input.time!==undefined&&(!Number.isFinite(input.time)||input.time<0||input.time>6))throw Error('Invalid rhythm, lead or time');setPattern(input.rhythm);selectLead(leads.findIndex(l=>l.name===input.lead));if(input.time!==undefined){state.time=input.time;state.playing=false;playLabel();}return{rhythm:state.key,lead:leads[state.lead].name,time:state.time,playing:state.playing};}})).catch(console.warn);}catch(e){console.warn(e);}}

// Pause at explicit mechanism stages without changing the selected lead.
document.querySelectorAll('[data-block-time]').forEach(button=>button.onclick=()=>{const b=beats.find(b=>b.q>.4);if(!b)return;state.time=b.q+Number(button.dataset.blockTime);state.playing=false;playLabel();});
