import {appearance} from './settings.js';
import {state,leads,phase,components,voltage} from './model.js';
import {network,junctions,transverse,conductionFrame} from './conduction.js';
const NS='http://www.w3.org/2000/svg';
function el(tag,attrs={},text){const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,v);if(text!==undefined)n.textContent=text;return n;}
const frontalAnatomy=`<path class="wall" d="M256 165 Q273 117 349 142 Q396 80 462 118 Q521 130 532 240 Q599 267 602 380 Q612 514 497 545 Q375 549 282 451 Q211 377 230 290 Q190 219 256 165Z"/>
<path class="right-cavity" d="M264 179 Q303 151 350 177 Q383 207 371 274 Q328 306 276 293 Q233 282 239 230 Q241 199 264 179Z"/>
<path class="left-cavity" d="M382 162 Q412 119 459 151 Q498 181 506 239 Q481 271 410 260 Q389 215 382 162Z"/>
<path class="right-cavity" d="M278 326 Q325 307 371 328 Q392 377 443 499 Q353 484 304 429 Q266 385 278 326Z"/>
<path class="left-cavity" d="M411 295 Q482 275 526 288 Q563 319 563 391 Q561 456 503 491 Q468 440 448 388 Q425 337 411 295Z"/>
<path class="valve" d="M274 310 L310 326 M363 307 L342 325 M405 277 L441 294 M508 261 L482 289"/>
<path class="vessel" d="M256 177 L245 111 M300 157 L295 101 M450 142 Q450 70 490 90 L513 145"/>
<g class="chamber-letters"><text x="305" y="236">RA</text><text x="445" y="210">LA</text><text x="336" y="383">RV</text><text x="505" y="370">LV</text></g>`;
const transverseAnatomy=`<path class="torso-reference" d="M167 298 Q190 156 384 167 Q628 168 654 339 Q668 488 426 512 Q211 515 167 370Z"/>
<path class="wall" d="M270 252 Q347 210 404 264 Q466 215 540 245 Q607 274 609 353 Q611 443 530 479 Q442 506 390 451 Q323 485 265 430 Q220 391 231 326 Q240 276 270 252Z"/>
<path class="right-cavity" d="M275 285 Q330 257 378 293 Q345 345 383 409 Q337 442 291 408 Q250 379 261 337 Q262 307 275 285Z"/>
<path class="left-cavity" d="M467 280 Q519 263 552 305 Q581 348 550 401 Q518 450 467 424 Q422 405 423 354 Q420 304 467 280Z"/>
<g class="chamber-letters"><text x="316" y="354">RV</text><text x="496" y="356">LV</text></g>
<g class="upstream-caption"><text x="410" y="41" text-anchor="middle">UPSTREAM SEQUENCE · ABOVE THIS VENTRICULAR SLICE</text><text x="233" y="65">SA</text><text x="351" y="65">AV</text><text x="418" y="65">His</text></g>`;
const frontLeadPositions=[[730,320],[560,579.8076],[260,579.8076],[90,135.2479],[730,135.2479],[410,614]];
const chestLeadPositions=[[185,235],[340,157],[526,159],[673,244],[716,357],[672,491]];
export function initHeart(container,onLead){container.replaceChildren();let view='frontal',labelsOn=false,leadsOn=true,lastLead=-1,lastLimb=1,lastChest=6;let svg,routeEls=[],leadEls=[],saNode,avNode,vector,anatomyGroup,activeConnector,flowText,altRoutes=[],snapshot={},blockMarker;
function pathFor(edge,points){const a=points[edge.from],b=points[edge.to];let mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];if(edge.kind==='purkinje')mid=[b[0],a[1]];if(edge.id==='left-atrium')mid=[400,130];if(view==='transverse'&&edge.kind==='atrial')mid=[(a[0]+b[0])/2,a[1]];return `M${a} Q${mid} ${b}`;}
function makeRoute(edge,d,extra=false){const base=el('path',{d,class:'conduction-rest',fill:'none','data-route':edge.id}),pulse=el('path',{d,class:'conduction-pulse',fill:'none',pathLength:100}),head=el('circle',{r:5.7,class:'impulse-head'});svg.append(base,pulse,head);const item={edge,base,pulse,head,length:base.getTotalLength()};(extra?altRoutes:routeEls).push(item);return item;}
function draw(){container.dataset.view=view;container.dataset.renderer='cross-section';svg=el('svg',{viewBox:'0 0 820 635',class:'cross-section',role:'img','aria-label':view==='frontal'?'Frontal four-chamber cross-section with connected conduction pathways and limb leads':'Transverse ventricular cross-section with chest leads and upstream conduction reference'});container.replaceChildren(svg);svg.innerHTML=`<defs><filter id="signal-glow"><feGaussianBlur stdDeviation="2"/></filter><marker id="vector-tip" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10Z" fill="currentColor"/></marker></defs><text class="orientation" x="95" y="90">PATIENT RIGHT</text><text class="orientation" x="631" y="90">PATIENT LEFT</text>`;
const anatomy=el('g',{class:'cutaway-anatomy'});anatomy.innerHTML=view==='frontal'?frontalAnatomy:transverseAnatomy;svg.append(anatomy);if(view==='transverse'){svg.append(el('text',{x:410,y:137,'text-anchor':'middle',class:'orientation'},'ANTERIOR / CHEST'),el('text',{x:410,y:547,'text-anchor':'middle',class:'orientation'},'POSTERIOR'));}
routeEls=[];altRoutes=[];leadEls=[];const points=view==='frontal'?junctions:transverse;
for(const e of network)makeRoute(e,pathFor(e,points));
// Explicit alternatives: blocked bundles use myocardial cross-septal spread; ectopy begins at its labeled ventricular focus.
makeRoute({id:'right-cross',side:-1,kind:'alternative'},`M${points.lp} Q${points.sept} ${points.rm}`,true);makeRoute({id:'left-cross',side:1,kind:'alternative'},`M${points.rp} Q${points.sept} ${points.lm}`,true);
makeRoute({id:'ectopic-left',kind:'alternative'},`M${points.la} Q${points.ll} ${points.lm}`,true);makeRoute({id:'ectopic-right',kind:'alternative'},`M${points.la} Q${points.sept} ${points.rm}`,true);
makeRoute({id:'flutter-loop',kind:'alternative'},view==='frontal'?'M292 190 C248 193 242 274 283 288 C336 295 351 224 292 190':'M235 85 C230 120 287 128 295 85 C292 58 236 57 235 85',true);
blockMarker=el('g',{class:'bundle-block-marker','aria-label':'Blocked bundle; schematic location'});blockMarker.append(el('circle',{r:14}),el('path',{d:'M-7 -7L7 7M-7 7L7 -7'}));svg.append(blockMarker);
saNode=el('circle',{cx:points.sa[0],cy:points.sa[1],r:8,class:'node sa-node'});avNode=el('circle',{cx:points.av[0],cy:points.av[1],r:8,class:'node av-node'});svg.append(saNode,avNode);
activeConnector=el('line',{class:'selected-lead-ray',x1:410,y1:355,x2:410,y2:355});vector=el('line',{class:'net-vector',x1:410,y1:355,x2:410,y2:355,'marker-end':'url(#vector-tip)'});svg.append(activeConnector,vector);
const positions=view==='frontal'?frontLeadPositions:chestLeadPositions;positions.forEach((p,i)=>{const index=view==='frontal'?i:i+6,l=leads[index],button=el('g',{class:'diagram-lead',role:'button',tabindex:0,'aria-label':'Select lead '+l.name,transform:`translate(${p})`,'data-lead':l.name});button.append(el('rect',{x:-33,y:-19,width:66,height:38,rx:7}),el('text',{'text-anchor':'middle',y:6},l.name));button.onclick=()=>onLead(index);button.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();onLead(index);}};svg.append(button);leadEls.push({button,index,p});});
anatomyGroup=el('g',{class:'optional-anatomy'});if(view==='frontal'){[['SA node',160,130,points.sa],['AV node',110,302,points.av],['His bundle',659,294,points.his],['Purkinje fibers',680,528,points.ll]].forEach(([name,x,y,target])=>{anatomyGroup.append(el('line',{x1:x,y1:y+6,x2:target[0],y2:target[1]}),el('text',{x,y,'text-anchor':'middle'},name));});}else{anatomyGroup.append(el('text',{x:128,y:426},'Right ventricle'),el('text',{x:600,y:559},'Left ventricle'));}svg.append(anatomyGroup);
flowText=document.getElementById('conductionStatus');document.getElementById('sectionTitle').textContent=view==='frontal'?'Frontal cutaway · limb leads':'Transverse section · V1–V6';document.getElementById('sectionNote').textContent=view==='frontal'?'A consistent four-chamber reference. The highlighted lead is a viewing direction.':'Same heart, sliced across the ventricles. SA → AV → His stays visible above the slice.';
document.getElementById('front').classList.toggle('active',view==='frontal');document.getElementById('side').classList.toggle('active',view==='transverse');}
function paint(item,sample){const {base,pulse,head,length}=item;const moving=!!sample.moving,progress=Math.max(0,Math.min(1,sample.progress||0)),recover=sample.recover||0;const chaos=sample.chaos||0;
const bbb=state.key==='rbbb'||state.key==='lbbb',blockedSide=state.key==='rbbb'?-1:1,slow=bbb&&(item.edge.kind==='alternative'||(item.edge.side===blockedSide&&!sample.blocked&&!item.edge.id.endsWith('-proximal'))),intact=bbb&&item.edge.side===-blockedSide,color=slow?'#ffad66':intact?'#70e5cf':'#ffe363';
base.style.stroke=recover>0?'#c38aff':sample.blocked?'#ff6678':sample.activated?color:slow?'#ffad66':'#65b9aa';base.style.opacity=recover>0?String(recover):sample.blocked?'.85':sample.activated?'.85':sample.enabled===false?'.10':slow?'.45':'.29';base.style.strokeWidth=String(recover>0?appearance.signal*.85:sample.activated?appearance.signal*.55:3);base.style.strokeDasharray=sample.blocked?'3 7':slow?'7 7':'';pulse.style.strokeWidth=String(appearance.signal);head.setAttribute('r',appearance.signal*.65+1);head.style.fill=color;head.style.stroke=color;head.style.filter=`drop-shadow(0 0 5px ${color})`;pulse.style.filter=`drop-shadow(0 0 3px ${color})`;
pulse.style.opacity=moving?'1':chaos>.2?String(chaos):'0';pulse.style.stroke=color;pulse.setAttribute('stroke-dasharray',chaos>.2?'100 0':`${Math.min(16,progress*100)} 100`);pulse.setAttribute('stroke-dashoffset',String(-Math.max(0,progress*100-16)));head.style.display=moving?'':'none';if(moving){const p=base.getPointAtLength(progress*length);head.setAttribute('cx',p.x);head.setAttribute('cy',p.y);} }
function render(t){if(lastLead!==state.lead){lastLead=state.lead;if(lastLead<6)lastLimb=lastLead;else lastChest=lastLead;const next=lastLead<6?'frontal':'transverse';if(!svg||next!==view){view=next;draw();}}
const f=conductionFrame(t),p=phase(t),dt=t-f.q;let samples=f.samples.map(s=>({...s}));
// Delay the blocked side through the explicitly drawn alternative route; never launch distal branches at QRS onset.
if(f.blocked){const baseTime=.065,side=f.blocked;for(const s of samples){if(s.side!==side)continue;if(s.id.endsWith('-proximal'))continue;if(s.id==='septal')continue;if(['left-bundle','right-bundle'].includes(s.id)){s.blocked=true;continue;}const stretch=(f.d-baseTime)/(.09-.018);let start=baseTime+Math.max(0,s.start-f.q-.018)*stretch,end=baseTime+Math.max(0,s.end-f.q-.018)*stretch;end=Math.min(f.d,end);s.enabled=true;s.progress=(dt-start)/(end-start);s.moving=dt>=start&&dt<=end;s.activated=dt>end&&t<f.recoveryCenter-f.rw;}}
if(f.ectopic){const timings={'left-upper':[.045,.085],'left-lower':[0,.045],'right-apex':[.075,.10],'right-upper':[.075,.115],'right-lower':[.10,.13]};for(const s of samples){if(s.kind==='atrial')continue;let interval=timings[s.id];if(s.kind==='tissue'&&s.parent&&timings[s.parent])interval=[timings[s.parent][1],f.d];if(interval){const[start,end]=interval;s.enabled=true;s.progress=(dt-start)/(end-start);s.moving=dt>=start&&dt<=end;s.activated=dt>end&&t<f.recoveryCenter-f.rw;}}}
routeEls.forEach((item,i)=>paint(item,samples[i]));altRoutes.forEach(item=>{let enabled=false,start=0,end=0;if(f.blocked&&item.edge.id===(f.blocked<0?'right-cross':'left-cross')){enabled=true;start=.008;end=.065;}if(f.ectopic&&item.edge.id.startsWith('ectopic')){enabled=true;start=0;end=item.edge.id==='ectopic-left'?.045:.075;}if(f.flutter&&item.edge.id==='flutter-loop'){paint(item,{enabled:true,moving:true,progress:((t%.2)+.2)% .2/.2});return;}paint(item,{enabled,moving:enabled&&dt>=start&&dt<=end,progress:enabled?(dt-start)/(end-start):0,activated:enabled&&dt>end&&dt<f.d});});
saNode.style.fill=f.saActive?'#fff4aa':'#476b68';avNode.style.fill=f.avHold?'#ffe363':'#476b68';avNode.setAttribute('r',f.avHold?10:8);
const points=view==='frontal'?junctions:transverse;blockMarker.style.display=f.blocked?'':'none';if(f.blocked){const target=f.blocked<0?points.rp:points.lp;blockMarker.setAttribute('transform',`translate(${target[0]},${target[1]+10})`);}
const lesson=document.getElementById('blockLesson');lesson.hidden=!f.blocked;container.dataset.blockedSide=f.blocked<0?'right':f.blocked>0?'left':'none';
if(f.blocked){const right=f.blocked<0,intact=right?'Left':'Right',delayed=right?'Right':'Left';document.getElementById('blockTitle').textContent=right?'RBBB · the right bundle is blocked':'LBBB · the left bundle is blocked';document.getElementById('blockDescription').textContent=`${intact} bundle conduction remains available. The ${delayed.toLowerCase()} ventricle is reached later through slower myocardial spread across the septum.`;document.getElementById('intactTitle').textContent=intact+' ventricle · intact bundle';document.getElementById('delayedTitle').textContent=delayed+' ventricle · delayed';const recovery=p.id==='T';document.getElementById('intactStatus').textContent=recovery?'Recovering':dt<0?'Waiting for His impulse':dt<.09?'Activating through intact pathway':'Activation completed';document.getElementById('delayedStatus').textContent=recovery?'Recovering':dt<.008?'No direct bundle conduction':dt<.065?'Impulse spreading across septum':dt<f.d?'Late activation through muscle':'Activation completed';document.getElementById('blockMoment').textContent=dt<0?'Follow the common SA → AV → His route, then watch the paths diverge.':dt<.065?'Early QRS: the intact side activates while slower spread crosses toward the blocked side.':dt<f.d?(right?'Late QRS: delayed rightward forces contribute to terminal R′ in V1 and terminal S in I / V6.':'Late QRS: delayed left ventricular forces contribute to a broad positive complex in I / V6 and negative complex in V1.'):'Pause on a step below to compare early activation with the delayed terminal QRS.';}
const originY=view==='frontal'?320:355;activeConnector.setAttribute('y1',originY);vector.setAttribute('y1',originY);const selected=leadEls.find(x=>x.index===state.lead);for(const l of leadEls){l.button.style.display=leadsOn?'':'none';l.button.classList.toggle('selected',l.index===state.lead);l.button.setAttribute('aria-pressed',String(l.index===state.lead));}activeConnector.style.display=leadsOn?'':'none';if(selected){activeConnector.setAttribute('x2',selected.p[0]);activeConnector.setAttribute('y2',selected.p[1]);}
const c=components(t),scale=80;vector.style.display=Math.hypot(c.x,c.y,c.z)>.04?'':'none';vector.setAttribute('x2',410+c.x*scale);vector.setAttribute('y2',originY+(view==='frontal'?c.y:-c.z)*scale);vector.style.color=p.id==='T'?'#c38aff':'#ffe363';vector.style.stroke=p.id==='T'?'#c38aff':'#ffe363';anatomyGroup.style.display=labelsOn?'':'none';svg.querySelector('.chamber-letters').style.display=labelsOn?'':'none';
const labels={'atrial-trunk':'SA node → atrial muscle','av-approach':'Atrial impulse → AV node','left-atrium':'Activation spreads through both atria','right-atrium':'Activation spreads through both atria',his:'AV node → His bundle','his-fork':'His bundle → bundle branches','left-proximal':'His bundle → left bundle','right-proximal':'His bundle → right bundle',septal:'Early QRS · septal activation','left-bundle':'Impulse descends the left bundle','right-bundle':'Impulse descends the right bundle','left-apex':'Left bundle → Purkinje branches','right-apex':'Right bundle → Purkinje branches'};
flowText.textContent=f.ectopic&&dt>=0&&dt<f.d?'Ventricular ectopic source · independent of SA impulse':labels[f.stage]|| (samples.some(s=>s.moving&&(s.kind==='purkinje'||s.kind==='tissue'))?'Purkinje branches → ventricular muscle':f.stage);
if(f.blocked&&dt>=.008&&dt<f.d)flowText.textContent=dt<.065?'Intact bundle activates first · slower spread crosses septum':`Delayed ${f.blocked<0?'right':'left'} ventricular activation · slow myocardial spread`;
container.dataset.electricalPhase=p.id;container.dataset.repolarizationVisible=String(samples.some(s=>s.recover>0));container.dataset.activeEdges=samples.filter(s=>s.moving).map(s=>s.id).join(',');container.dataset.avHold=String(f.avHold);snapshot={view,stage:flowText.textContent,activeEdges:samples.filter(s=>s.moving).map(s=>s.id),repolarization:samples.some(s=>s.recover>0)};
}
return{render,setLeads(v){leadsOn=v;},setLabels(v){labelsOn=v;},view(name){onLead(name==='side'?lastChest:lastLimb);},getSnapshot(){return snapshot;}};
}
