import {state,phase,currentBeat,leads} from './model.js';
const NS='http://www.w3.org/2000/svg';
const paths={
 frontal:{anterior:'M533 288Q599 323 600 380Q607 472 542 520L511 486Q564 447 563 391Q565 333 533 288Z',inferior:'M480 480Q498 499 529 477L566 514Q530 544 497 545L468 515Z'},
 transverse:{anterior:'M405 264Q466 215 540 245Q586 263 602 310L563 320Q541 272 495 278Q449 276 423 308Z',inferior:'M435 408Q480 458 550 401L590 428Q550 488 493 490Q451 489 412 451Z'}
};
export function createInjuryOverlay(svg,view,hover){
 const group=document.createElementNS(NS,'g');group.classList.add('injury-region');group.innerHTML='<defs><pattern id="injury-hatch" width="12" height="12" patternUnits="userSpaceOnUse"><path d="M0 12L12 0" stroke="#ffd0d8" stroke-width="2" opacity=".65"/></pattern></defs><path class="injury-base"/><path class="injury-hatch" fill="url(#injury-hatch)"/>';
 // Keep the injury under electrical pathways, inside the myocardial wall.
 const anatomy=svg.querySelector('.cutaway-anatomy');anatomy.after(group);
 let previous='';
 function render(t){const active=state.key==='anterior'||state.key==='inferior';group.style.display=active?'':'none';if(!active)return;const key=state.key;if(previous!==key){previous=key;for(const p of group.querySelectorAll('path.injury-base,path.injury-hatch'))p.setAttribute('d',paths[view][key]);group.setAttribute('aria-label',key==='anterior'?'Anterior/apical LV injury territory, projected schematic':'Inferior LV injury territory, schematic');}
 const p=phase(t),b=currentBeat(t),local=t-(b?.q??0);const activation=p.id==='QRS'&&local>=.015;group.dataset.stage=activation?'activation':p.id==='ST'?'injury-current':p.id==='T'?'recovery':'rest';group.querySelector('.injury-base').style.stroke=activation?'#ffe363':p.id==='T'?'#c38aff':'#ff7b9f';group.querySelector('.injury-base').style.fillOpacity=p.id==='ST'?'.85':'.5';
 }
 hover.bind(group,'Ischemic / injured LV myocardium · hatched region');return{render};
}
export function initInjuryLesson(){
 const panel=document.getElementById('injuryLesson');panel.innerHTML=`<span class="eyebrow">FROM INJURED CELLS TO THE ECG</span><h3 id="injuryTitle"></h3><p id="injuryCause"></p><div class="injury-chain"><span>Example coronary blockage</span><b>→</b><span>Reduced oxygen delivery</span><b>→</b><span>Altered cell voltages</span><b>→</b><span>Injury currents / ST shift</span></div><p id="injuryMoment"></p><svg class="injury-cell-chart" viewBox="0 0 600 200" role="img" aria-label="Qualitative normal and ischemic ventricular cell action potentials; ischemic cells have a less negative resting potential and a smaller, shorter action potential"><rect x="135" y="20" width="180" height="135" fill="#ff6c8c" opacity=".12"/><path d="M20 145L90 145L105 30L120 45L300 65Q350 75 390 140L570 145" fill="none" stroke="#70e5cf" stroke-width="4"/><path d="M20 123L90 123Q108 80 132 68L240 89Q282 108 310 123L570 123" fill="none" stroke="#ff8d9d" stroke-width="4" stroke-dasharray="8 5"/><line id="injuryCellCursor" y1="20" y2="153" stroke="#ffe363" stroke-width="2"/><text x="28" y="182" fill="#70e5cf">Healthy cell</text><text x="285" y="182" fill="#ff8d9d">Ischemic cell</text><text x="145" y="15" fill="#f5c2ce">Plateau voltage difference</text></svg><p class="injury-cell-note">Qualitative ventricular-cell potentials, not surface ECG traces. An ischemic cell can have a less negative resting potential and a smaller, shorter action potential. This diagram illustrates a mechanism; it is not a numerical calculation of the displayed ECG.</p><div class="injury-actions"><button id="injuryST">Inspect ST segment</button><button id="injuryT">Compare T wave</button><button id="injuryLead">View facing lead</button></div><p id="injuryLeadNote"></p><p class="injury-limit">Hatching marks an illustrative injury territory, not a proven scar or the size of an infarct. Injury persists throughout the cycle; the passing impulse does not create it. Coronary anatomy and ECG localization vary.</p>`;
 panel.querySelector('#injuryST').onclick=()=>document.querySelector('[data-phase="ST"]').click();panel.querySelector('#injuryT').onclick=()=>document.querySelector('[data-phase="T"]').click();panel.querySelector('#injuryLead').onclick=()=>{const name=state.key==='anterior'?'V3':'III';document.querySelectorAll('.lead-button')[leads.findIndex(l=>l.name===name)].click();};
 function render(t){const anterior=state.key==='anterior',active=anterior||state.key==='inferior';panel.hidden=!active;if(!active)return;
 panel.querySelector('#injuryTitle').textContent=anterior?'Anterior ST-elevation example · injured LV region':'Inferior ST-elevation example · injured LV region';
 panel.querySelector('#injuryCause').textContent=anterior?'An acute LAD-territory occlusion is one possible cause of anterior/apical myocardial ischemia. The hatched wall is a projected teaching territory; the transverse view places it anteriorly.':'An RCA or circumflex-territory occlusion can injure inferior LV myocardium. The hatched wall is a schematic inferior territory; coronary dominance affects the actual distribution.';
 const p=phase(t);panel.dataset.phase=p.id;panel.querySelector('#injuryMoment').textContent=p.id==='QRS'?'QRS: activation spreads into the LV, including the injured region. The gold border marks the illustrative arrival of activation, not new tissue damage.':p.id==='ST'?'ST: healthy and ischemic myocardium do not have the same electrical state. Injury currents, including changes to the reference baseline, can make the ST segment appear elevated in facing leads. This is not a taller T wave.':p.id==='T'?'T wave: ventricular repolarization. Ischemia can also change T-wave shape, but ST elevation is a segment shift, not simply increased repolarization amplitude.':'The injury remains present between beats. Differences in resting membrane potential also contribute to injury currents and the reference-baseline shift.';
 const b=currentBeat(t),u=Math.max(0,Math.min(1,(t-(b?.q??0)+.08)/.6));const x=20+550*u;panel.querySelector('#injuryCellCursor').setAttribute('x1',x);panel.querySelector('#injuryCellCursor').setAttribute('x2',x);
 panel.querySelector('#injuryLead').textContent='View '+(anterior?'V3':'III');panel.querySelector('#injuryLeadNote').textContent=`Selected lead: ${leads[state.lead].name}. ${anterior?'V2–V4 face anterior forces in this example.':'II, III and aVF face inferior forces in this example; I and aVL show reciprocal depression.'} The sign depends on the lead’s view of the total electrical field, not one cell’s voltage.`;
 }
 return{render};
}
