import {validateRecord,parseCSV,parseWFDB} from './recording-data.js';
const $=id=>document.getElementById(id);let record=null,time=0,playing=false,last=performance.now(),lastDraw=0;
function load(r){record=validateRecord(r);time=0;playing=false;$('playRecord').textContent='▶ Play';$('recording').hidden=false;$('lead').replaceChildren(...record.leads.map(l=>new Option(l,l)));$('seek').max=record.duration;$('seek').value=0;$('meta').textContent=`${record.leads.length} leads · ${record.sampleRateHz} Hz · ${record.duration.toFixed(2)} seconds · mV`;$('status').textContent='Recording ready. Select a lead or drag the time slider.';draw();}
$('files').onchange=async()=>{const files=[...$('files').files];try{if(files.some(f=>f.size>64*1024*1024))throw Error('Each file must be under 64 MB. Use the converter to select a shorter segment.');const h=files.find(f=>/\.hea$/i.test(f.name));if(h){const d=files.find(f=>/\.dat$/i.test(f.name));if(!d)throw Error('Select the matching .hea and .dat files together.');load(parseWFDB(await h.text(),await d.arrayBuffer(),d.name));}else{if(files.length!==1)throw Error('Select one JSON/CSV file or one WFDB pair.');const f=files[0],text=await f.text();load(/\.csv$/i.test(f.name)?parseCSV(text):JSON.parse(text));}}catch(e){$('status').textContent='Could not open: '+e.message;}finally{$('files').value='';}};
$('demo').onclick=async()=>{try{const response=await fetch('examples/synthetic.json');if(!response.ok)throw Error('Sample unavailable');load(await response.json());$('status').textContent='Synthetic demonstration recording — not a patient ECG.';}catch(e){$('status').textContent=e.message;}};
$('playRecord').onclick=()=>{playing=!playing;$('playRecord').textContent=playing?'Ⅱ Pause':'▶ Play';};$('seek').oninput=()=>{time=+$('seek').value;playing=false;$('playRecord').textContent='▶ Play';draw();};for(const id of ['lead','gain','window'])$(id).onchange=draw;
$('exportRecord').onclick=()=>{const {duration,...portable}=record;const url=URL.createObjectURL(new Blob([JSON.stringify(portable)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='heartscope-recording.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function draw(){if(!record)return;const canvas=$('recordCanvas'),rect=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2),w=rect.width,h=rect.height;canvas.width=w*d;canvas.height=h*d;const c=canvas.getContext('2d');c.scale(d,d);const span=Math.min(+$('window').value,record.duration),start=Math.min(Math.max(0,time-span*.3),record.duration-span),gain=+$('gain').value,left=48,right=w-16,base=h/2,channel=record.leads.indexOf($('lead').value),x=t=>left+(t-start)/span*(right-left);c.font='12px sans-serif';for(let mv=-4;mv<=4;mv+=.5){const y=base-mv*gain;c.strokeStyle=mv===0?'#506d77':'#203943';c.beginPath();c.moveTo(left,y);c.lineTo(right,y);c.stroke();c.fillStyle='#acc1cc';if(y>16&&y<h-22)c.fillText(mv+'',5,y+4);}for(let t=Math.ceil(start*5)/5;t<start+span;t+=.2){c.strokeStyle='#203943';c.beginPath();c.moveTo(x(t),20);c.lineTo(x(t),h-24);c.stroke();if(Math.round(t*5)%5===0){c.fillStyle='#acc1cc';c.fillText(t.toFixed(1)+' s',x(t),h-6);}}c.save();c.beginPath();c.rect(left,20,right-left,h-44);c.clip();c.strokeStyle='#ffe363';c.lineWidth=2.5;c.beginPath();let first=true;for(let i=Math.floor(start*record.sampleRateHz);i<=Math.min(record.samples.length-1,Math.ceil((start+span)*record.sampleRateHz));i++){const px=x(i/record.sampleRateHz),y=base-record.samples[i][channel]*gain;first?c.moveTo(px,y):c.lineTo(px,y);first=false;}c.stroke();c.strokeStyle='#70e5cf';c.beginPath();c.moveTo(x(time),20);c.lineTo(x(time),h-24);c.stroke();c.restore();c.fillStyle='#acc1cc';c.fillText('mV',5,14);$('seek').value=time;$('position').textContent=time.toFixed(2)+' s';const v=record.samples[Math.min(record.samples.length-1,Math.round(time*record.sampleRateHz))][channel];$('reading').textContent=`Lead ${record.leads[channel]} at ${time.toFixed(3)} s: ${v.toFixed(3)} mV. Display gain ${gain} pixels/mV; original values preserved.`;}
new ResizeObserver(draw).observe($('recordCanvas'));function frame(now){if(record&&playing){time+=(now-last)/1000*+$('speedRecord').value;if(time>record.duration)time=0;if(now-lastDraw>33){draw();lastDraw=now;}}last=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
