const steps=[
 ['Start with the big picture','An ECG records voltage differences measured from the body surface. It does not show a single cell’s action potential or directly measure contraction. This app links a simplified heart diagram to an illustrative ECG.','Try normal sinus rhythm first. “Sinus” means the normal impulse starts in the SA node.'],
 ['Follow the impulse','In a normal beat, the SA node starts atrial activation. The AV node delays conduction, then the His bundle, bundle branches and Purkinje fibers distribute the impulse to ventricular muscle.','Yellow marks activation; purple marks recovery. The electrical structures stay labeled. Hover over a label or structure—or tap it on a phone—to learn where it sits.'],
 ['Read the waves','The P wave represents atrial depolarization. QRS represents ventricular depolarization. The T wave represents ventricular repolarization. A positive deflection is upward and a negative deflection is downward.','The strip’s moving cursor and heart share the same teaching timeline. A surface ECG is the combined electrical field, not a tracing of one cell.'],
 ['Slow down and inspect','Pause freezes the model. Drag “Explore time” or select a point on the enlarged beat to inspect an instant. The numbered steps in a bundle-block lesson jump to useful moments.','1× Study is already ten times slower than real time. 1.25× is slightly faster; 2.5× is the maximum. The ECG’s time labels and heart rate stay unchanged.'],
 ['Change your viewing direction','A lead is an electrical viewpoint. Limb leads I, II, III, aVR, aVL and aVF use the frontal view. Chest leads V1–V6 use the transverse view. The same event can appear positive in one lead and negative in another.','Choose II, then aVR, then V1 and V6. Lead territories are viewing regions, not isolated signal sources. “Plumbing · flow / US” adds circulation and a schematic echo-style view linked to the ECG clock.'],
 ['Compare pathology and cells','Change the rhythm/pattern menu to RBBB. The red × marks a schematic block; mint shows the intact pathway and orange shows delayed spread. Hover or tap the SA/AV node for a separate cellular action-potential illustration.','Anterior and inferior ST-elevation examples highlight injured myocardium and compare healthy versus ischemic cells. The nodal cellular illustration is not time-aligned to the ECG. “Customize this view” adjusts trace thickness, heart-signal thickness and display gain.'],
 ['Explore real recordings when ready','“Open your ECG recordings” lets you try a sample or open supported digital ECG files. Those measured voltages are displayed separately from the synthetic heart model.','Start with the teaching model, compare leads, then compare patterns. This is an educational explanation, not a tool for diagnosing a patient.']
];
const dialog=document.createElement('dialog');dialog.className='tutorial-dialog';dialog.setAttribute('aria-labelledby','tutorial-title');dialog.innerHTML='<form method="dialog"><button class="tutorial-close" aria-label="Close tutorial">✕ Close</button></form><p id="tutorial-count" class="eyebrow"></p><h2 id="tutorial-title"></h2><p id="tutorial-text"></p><p id="tutorial-try"></p><div class="tutorial-actions"><button id="tutorial-back">Back</button><button id="tutorial-next" class="primary">Next</button></div>';document.body.append(dialog);let index=0;
function render(){const [title,text,tryIt]=steps[index];dialog.querySelector('#tutorial-count').textContent=`FIRST-YEAR MEDICAL STUDENT GUIDE · ${index+1} / ${steps.length}`;dialog.querySelector('#tutorial-title').textContent=title;dialog.querySelector('#tutorial-text').textContent=text;dialog.querySelector('#tutorial-try').textContent=tryIt;dialog.querySelector('#tutorial-back').disabled=index===0;dialog.querySelector('#tutorial-next').textContent=index===steps.length-1?'Start exploring':'Next';}
document.getElementById('tutorialBtn').onclick=()=>{index=0;render();dialog.showModal();};dialog.querySelector('#tutorial-back').onclick=()=>{index=Math.max(0,index-1);render();};dialog.querySelector('#tutorial-next').onclick=()=>{if(index===steps.length-1)dialog.close();else{index++;render();}};dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});
